### ISSUE TITLE
Where is the "transf.txt"?

### ISSUE THREAD

**Issue by neuralchen** [tehret/mosaic-to-mosaic#2]

**Comment by tehret** [comment]
There's a "transf.txt" generated by "generate_burst.py". However this file is never used by the rest of the pipeline as the transforms are estimated directly from the data using the inverse compositional algorithm directly on the burst.

**Comment by neuralchen** [comment]
Thx for your reply.
N i got another trouble, the ‘iio’ module seems dont work.
The bug:
IIO_ERROR("python assert_quality.py --input gharbi_finetuned.tiff --ref ./data/kodak/kodim19.png"): png_create_read_struct fail

**Comment by tehret** [comment]
You could try reinstalling the pip package. If it still doesn't work you can contact the author of the module or change the code to use your favorite image io library.
