### ISSUE TITLE
Missing network weights at fine tune stage

### ISSUE THREAD

**Issue by TomHeaven** [tehret/mosaic-to-mosaic#3]
I'm trying to run 
```
./finetuning_toy.sh data/kodak/kodim19.png 10 5
```
However, it seems a weight named `dmcnn_44_B2Bres.pth` is missing in` finetune.py`. Here is a parameter specifying the default path of it:
```python3
parser.add_argument("--net", type=str, default="/mnt/adisk/tehret/demosaicking/out/dmcnn_44_B2Bres.pth",
```

Looking forward to your reply!

**Comment by tehret** [comment]
If you look carefully at the code, this argument is actually never used. The weights loaded by the code are the ones provided in `demosaic_torch` which correspond to the network from " Deep Joint Demosaicking and Denoising" by Gharbi et al.

I removed this argument that I forgot when cleaning the code to remove any confusion.

**Comment by TomHeaven** [comment]
Thanks for the quick answer. The code hangs on "Loading Weights" made me think the cause might be lacking of weight files.  In fact, it's running in loops and I just need to wait.
