### ISSUE TITLE
finetuning_real on the example produces white images

### ISSUE THREAD

**Issue by bruno-31** [tehret/mosaic-to-mosaic#4]
Hello,

I compiled mInverse_bayer without a problem.
However when I try to run the algorithm on real images from HDR+ with the command
`finetuning_real.sh data/hdrplus/1/%d.tiff 9 0.015` 

It does not throw any errors but the result is that I get  is always a white image.

Would you have any idea about this ?
Best

**Comment by tehret** [comment]
I have tested the code on a new clean installation and did not encounter any problem. My intuition would be that your image viewer doesn't display properly tif images (the range of the real images is 16bits compared to the 8bits synthetic data).

I use https://github.com/kidanger/vpv if you want to try this possibility (another image viewer might also do the job, it's just that I know that this one doesn't have this problem for sure).

**Comment by bruno-31** [comment]
Hi,

Thank you for your prompt reply. 
You are right : for some reasons I could not read/convert this .tiff with other image viewers but it works with vpv (thanks btw I did not know this software).

Thank you
Bruno
